AUDIO_SAMPLE_RATE = 16_000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH_BYTES = 2
AUDIO_CHUNK_SECONDS = 0.1
AUDIO_PRE_ROLL_SECONDS = 0.3

STREAM_SEMANTIC_SILENCE_SECONDS = 2
STREAM_HARD_SILENCE_SECONDS = 5
STREAM_FALLBACK_NEW_WORD_THRESHOLD = 3
STREAM_SPEECH_CONTINUE_THRESHOLD_RATIO = 0.6
STREAM_SPEECH_HANGOVER_SECONDS = 0.3
DEFAULT_SILENCE_THRESHOLD = 500
