AUDIO_SAMPLE_RATE = 16_000
AUDIO_CHANNELS = 1
AUDIO_SAMPLE_WIDTH_BYTES = 2
AUDIO_CHUNK_SECONDS = 0.2
AUDIO_PRE_ROLL_SECONDS = 1.0

STREAM_HARD_SILENCE_SECONDS = 2
STREAM_TRANSCRIPTION_INTERVAL_SECONDS = 1
STREAM_TRANSCRIPT_AGREEMENT_COUNT = 2
FINAL_TRANSCRIPTION_OVERLAP_SECONDS = 0.4
STREAM_SPEECH_CONTINUE_THRESHOLD_RATIO = 0.6
STREAM_SPEECH_HANGOVER_SECONDS = 0.1
STREAM_BACKGROUND_POLL_SECONDS = 0.4
DEFAULT_SILENCE_THRESHOLD = 400
